# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
        run: echo hello
  
  print_word:
    docker:
      image: circleci/node:13.8.0 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
        run: echo word

  # envValues:
  #   docker:
  #     image: circleci/node:13.8.0 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

  #   steps:
  #       name: Nejah
  #       run: echo $envValueForThisProject

workflows:
  welcome:
    
    jobs:
      - welcome/run
      - print_hello
      - print_word:
        requires:
          -print_hello
      # -envValues